# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jF3lb8zO3N8xNdO0AidjyimUMGjy0Iwo
"""

from flask import Flask
from flask_restx import Api, Resource, fields
import numpy as np
import joblib

app = Flask(__name__)
api = Api(app, version='1.0', title='Popularity Prediction API',
          description='Predice la popularidad de canciones a partir de sus características')

ns = api.namespace('predict', description='Modelo de regresión')

modelo = joblib.load("reg_popularidad.pkl")

input_model = api.model('SongFeatures', {
    'duration_ms': fields.Float(required=True),
    'explicit': fields.Integer(required=True),
    'danceability': fields.Float(required=True),
    'energy': fields.Float(required=True),
    'key': fields.Integer(required=True),
    'loudness': fields.Float(required=True),
    'mode': fields.Integer(required=True),
    'speechiness': fields.Float(required=True),
    'acousticness': fields.Float(required=True),
    'instrumentalness': fields.Float(required=True),
    'liveness': fields.Float(required=True),
    'valence': fields.Float(required=True),
    'tempo': fields.Float(required=True),
    'time_signature': fields.Integer(required=True)
})

@ns.route('/')
class PopularityRegressor(Resource):
    @ns.expect(input_model)
    def post(self):
        data = api.payload
        features = np.array([[data[k] for k in input_model.keys()]])
        pred = modelo.predict(features)[0]
        return f'{pred:.2f}'

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0', port=5000)